### ISSUE TITLE
i'm sorry in advance but..

### ISSUE THREAD

**Issue by Koleotank** [mohammedh123/ProjectHekate#17]
even if i installed ANTLR4 properly, i keep getting 8 errors and 4 warnings when opening projecthekate.core, what do i do now?
![image](https://user-images.githubusercontent.com/38538179/47234316-bc924f00-d3d5-11e8-8c64-7e9523301954.png)

**Comment by mohammedh123** [comment]
what version of visual studio are you on? currently installing a fresh install of vs 2017 community edition to try to duplicate your error(s)

**Comment by mohammedh123** [comment]
i would guess its failing to build a few of the project libraries; can you paste your entire error list?

**Comment by mohammedh123** [comment]
so i got it working off of a fresh install by:
1. installing antlr language support for vs (step 2 of https://github.com/tunnelvisionlabs/antlr4cs)
2. following this SO answer (because i was getting build framework dll issues): https://stackoverflow.com/a/47947104

lemme know how it goes

**Comment by Koleotank** [comment]
ok, i'm using VS2017

![image](https://user-images.githubusercontent.com/38538179/47239064-83151000-d3e4-11e8-9ee3-29db91280f50.png)

![image](https://user-images.githubusercontent.com/38538179/47239075-8c9e7800-d3e4-11e8-89f3-9cecfcb84b52.png)

**Comment by mohammedh123** [comment]
enable nuget package restore to download the nuget packages

also looks like you need to install antlr language support for vs (hence why those libraries arent compiling)

**Comment by Koleotank** [comment]
oh okey

**Comment by Koleotank** [comment]
![image](https://user-images.githubusercontent.com/38538179/47240859-f40af680-d3e9-11e8-8a48-cdac9cf0ae18.png)
still, this happens

**Comment by mohammedh123** [comment]
right now, you have a library set as the startup project. right click the gui project and set _that_ as the startup project

**Comment by Koleotank** [comment]
yay it worked, thanks!!!

**Comment by mohammedh123** [comment]
![thumbs up](https://emilh.net/img/thumbs-up.gif)

**Comment by Koleotank** [comment]
(anyways, how do i add a danmaku script to the engine)

**Comment by mohammedh123** [comment]
add the script (or edit the existing sample script) at `ProjectHekate.GUI/Resources/Scripts/` and then take a look at `ProjectHekate.GUI/Screens/TestScreen.cs`
